tema1
CppRemoteLearning/2022 pull request #13
Opened 2022-12-09 16:27 UTC by andreea-bumbac

tema 1

2022-12-09 16:34 UTC, CristianIonutIonescu requested changes
Salutare,

Se pare ca gitignore-ul  nu a mers cum trebuie. Incearca te rog sa ai toate fisierele generate de cmake intr-un folder separat build pe care sa-l pui in .gitignore.

Pe langa asta, am lasat un comment in plus legat de folosirea

`usign namespace std`

2022-12-09 16:34 UTC, CristianIonutIonescu commented on Header.h
> +using namespace std;
desi este mult mai lejer sa dam include la un namespace cu totul, acest lucru nu este ok deoarece o sa ne aduca in proiect tot namespace-ul marind size-ul aplicatiei fara rost.

2022-12-09 17:57 UTC, marisvali approved these changes
Good job!

2022-12-09 19:05 UTC, CristianIonutIonescu reviewed
Sorry for late reply.
Scopul temei a fost îndeplinit dar commentul meu legat de namespace nu. Te rog rezolva și acel lucru

2022-12-10 05:38 UTC, marisvali approved these changes

2022-12-10 05:40 UTC, merged