First homework
CppRemoteLearning/2022 pull request #14
Opened 2022-12-09 17:20 UTC by crissty21

first pull request on someone else's repository...
Uuu interesting !

2022-12-09 17:31 UTC, marisvali requested changes
Great job!
O mica corectura doar, CMakeLists.txt are 11 linii, trebuie sa aiba maxim 10.

2022-12-09 18:34 UTC, crissty21 commented
fixed issues

2022-12-09 19:11 UTC, CristianIonutIonescu requested changes
Te rog nu șterge codeowners și/sau folderul .github

2022-12-10 09:13 UTC, crissty21 reviewed
nu am idee care a fost treaba cu .github, dar l-am creat de la zero si am adaugat ce lipsea

2022-12-10 10:18 UTC, marisvali approved these changes
Super, good job!

2022-12-10 10:18 UTC, merged