draft: Upload homework 2
CppRemoteLearning/2022 pull request #16
Opened 2022-12-13 14:31 UTC by oprisor-adrian

2022-12-13 18:12 UTC, enachebogdan requested changes
Great job Adrian, code looks clean and well written and you implemented most of the required functionality. Most of my comments relate to minor issues, your homework looks very good overall.

2022-12-13 18:12 UTC, enachebogdan commented on course_2_homework/src/read_write_xml.cc
> +	return false;
you don't need to return, the function will exit after throwing anyway. nice that that you're using exceptions.

2022-12-13 18:12 UTC, enachebogdan commented on course_2_homework/src/read_write_xml.cc
> +	return false;
same here, no need to return after throw.
since these functions throw errors, ideally you should call them in a try{} - catch() scope.

2022-12-13 19:18 UTC, enachebogdan commented on course_2_homework/include/manage_store.h
> +#ifndef MANAGE_STORE_INCLUDE_MANAGE_STORE_H_
Cristi says Google guideline recommends #ifndef instead of #pragma, personal opinion is that you can use whichever but is good to know about both, so no need to change anything here

2022-12-15 18:34 UTC, CristianIonutIonescu requested changes
Left some minor comments about include what you need and a question.
Most important remark:
Move constructors and assignment operators are not correct. Re-read about them and redo them

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/include/product.h
> +#include <tuple>
you can get rid of this include

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/include/product.h
> +#include <iostream>
you can get rid of this include here.
If you need it in source file, include it there
https://google.github.io/styleguide/cppguide.html#Include_What_You_Use

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/include/product.h
> +  void visit(void (*f)(unsigned int&,std::string&,std::string&,unsigned int&,float&));
please check std::function<> object

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/include/store_manager.h
> +#include "xml_reader_writer.h"
same as above, if you don't use them in headers, don't include them

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/include/xml_parser.h
> +#include <iostream>
remove this

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/src/xml_parser.cc
> +  unsigned int id = std::stoul(unconverted_data[0]);
what if uncoverted_data size is less than 5?

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
> +StoreManager::StoreManager(StoreManager&& other) noexcept
re-read about move constructors, why do you initialise the members?

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
> +  other.no_of_products_ = 0;
we don't care about other data anymore, it should have been an empty shell

2022-12-15 18:34 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
> +StoreManager& StoreManager::operator=(StoreManager&& other) noexcept{
that's not how a move assigment operator should look

2022-12-16 10:19 UTC, oprisor-adrian commented on course_2_homework/src/xml_parser.cc
> +  unsigned int id = std::stoul(unconverted_data[0]);
I'm going to have an error because he's going to try to convert an element that doesn't exist. I can fix this issue by introducing a condition that checks the size of the vector.
`try{
   if(unconverted_data.size() == 5){
     // make conversion
   }
   throw std::invalid_argument("File contain incomplete product data set. Check it!");
}
catch(...){
  // do something
}`

2022-12-16 14:44 UTC, CristianIonutIonescu reviewed
Please fix latest comments and I'll approve afterwards

2022-12-16 14:44 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
> +  data_.clear();
no need to clear by hand, C++ runtime will take care of it

2022-12-16 14:44 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
>    for(auto iterator : other.data_)
your container knows how to implement std::move, no need to move the objects ourselves (might confuse the compiler)

2022-12-16 14:44 UTC, CristianIonutIonescu commented on course_2_homework/src/store_manager.cc
>      data_.clear();
same comments as for move constructor

2022-12-19 12:29 UTC, enachebogdan approved these changes

2022-12-19 13:05 UTC, merged