Lpitu tema2
CppRemoteLearning/2022 pull request #17
Opened 2022-12-13 17:42 UTC by Lys4nder

2022-12-13 18:41 UTC, enachebogdan requested changes
Great job, code loos good, you implemented most of the required functionality. My comments are only for small issues, i'll have a second look once you've added the file parsing logic.

2022-12-13 18:41 UTC, enachebogdan commented on product.cpp
> +#include "store.hpp"
did you mean to include product.hpp instead? don't think you need store class in here.

2022-12-13 18:41 UTC, enachebogdan commented on product.cpp
> +{ cout << "copy constructor called\n"; }
even for one-liner functions, for readability is better to use {} on different lines and use indentation, like you used for the destructor for example. you can apply this for getters and setters as well.

2022-12-13 18:41 UTC, enachebogdan commented on product.hpp
> +    public:
for better visibility, usually we indent public/private/protected differently from the members under them. You can either remove spacing for public: or add another tab to everything under the category.

2022-12-13 18:41 UTC, enachebogdan commented on product.hpp
> +using namespace std;
usually we recommend against the using keyword for the entire namespace, instead write std::cout or whatever you need.

2022-12-13 18:41 UTC, enachebogdan commented on xmlClass.hpp
> +#include "rapidXML/rapidxml.hpp"
good thing that you used an external parcer, it wouldn't be a problem if you implemented your own solution anyway.

2022-12-13 18:41 UTC, enachebogdan commented on store.cpp
> +        for (int i=0; i<products.size(); i++)
try using range-based for loop or iterators to parce your vector

2022-12-14 12:37 UTC, Lys4nder commented on .gitignore
> +/rapidXML
sure! i will make sure to remove the folder from .gitignore. Is is mandatory to modify the CMake file as well, as there are only hpp's, not cpp's in the library folder?

2022-12-15 16:05 UTC, Lys4nder commented
am dat push la versiunea completa

2022-12-15 18:09 UTC, CristianIonutIonescu requested changes
Mentioning here 2 things that I saw in multiple files:
1. [Order or declaring ](https://google.github.io/styleguide/cppguide.html#Declaration_Order)
2. ALL if/else/for/while statements must have the body clearly defined between { }even if it's one line:
```
if(..) {
} else {
}
for(...) {
}
//etc
```

2022-12-15 18:09 UTC, CristianIonutIonescu commented on XMLObject.cpp
> +                std::cout << "file '" << fname << "' opened\n";
if the file not found/cannot be opened why are we still trying to read from it?

2022-12-15 18:09 UTC, CristianIonutIonescu commented on CMakeLists.txt
> +include_directories(/usr/include/rapidxml)
might not be needed if
1. target_include_directories(point to correct interface)
2. you should include it after you checked for the presence of the library

2022-12-15 19:48 UTC, Lys4nder commented
done 😄

2022-12-15 19:59 UTC, CristianIonutIonescu approved these changes

2022-12-19 12:06 UTC, enachebogdan approved these changes

2023-02-01 22:52 UTC, merged