Bmereu tema2
CppRemoteLearning/2022 pull request #18
Opened 2022-12-14 06:24 UTC by 914-Mereu-Bianca

2022-12-14 07:59 UTC, CristianIonutIonescu requested changes
Hello,

Good job with the PR. I have left some minor comments on it but overall is looking great.

2022-12-14 07:59 UTC, CristianIonutIonescu commented on repository/Repository.cpp
> +    for(auto it = this->v.begin(); it != this->v.end(); it++){
minor:
Use pre-increment operator ( ++it) as it's better optimised.
The compiler already does it for you behind the scenes but it's a good practice to write it this way

2022-12-14 07:59 UTC, CristianIonutIonescu commented on repository/Repository.cpp
> +Repository::Repository() {}
you could write both as =default

2022-12-14 07:59 UTC, CristianIonutIonescu commented on model/Product.h
> +    Product(Product&& p)=default;
missing move operator

2022-12-14 07:59 UTC, CristianIonutIonescu commented on repository/Repository.h
> +    Repository(Repository && r)=default;
missing move/copy operators to have Rule of 5 complete

2022-12-14 07:59 UTC, CristianIonutIonescu commented on main.cpp
> +using namespace std;
please don't include the whole std namespace in your project. It's bad practice

2022-12-14 12:23 UTC, enachebogdan commented on repository/Repository.h
> +    std::vector<Product> v;
Surely you can find a better name than "v" for your member

2022-12-16 08:48 UTC, CristianIonutIonescu approved these changes

2022-12-16 16:57 UTC, merged