Tema2
CppRemoteLearning/2022 pull request #19
Opened 2022-12-14 10:07 UTC by crissty21

2022-12-14 12:16 UTC, enachebogdan requested changes
Good work Cristi, code looks clean and well written. I understand that this is just an initial draft, the homework requirement is to implement all "rule of five" functions, so I'm looking forward to see your update.

2022-12-14 12:16 UTC, enachebogdan commented on tema2/XmlParser.cpp
> +        std::cout << "file not opened";
you could also return from function, otherwise it will try reading from a file that's not open

2022-12-14 12:16 UTC, enachebogdan commented on tema2/headers/XmlParser.h
> +#include <fstream>
if you don't need a header in your .h files, it's good practice to include them in the .cpp file where you actually use it

2022-12-14 16:32 UTC, crissty21 reviewed
fixed everything

2022-12-14 16:56 UTC, CristianIonutIonescu commented on .vscode/settings.json
> +{
Add .vscode to ignore list

2022-12-15 06:28 UTC, CristianIonutIonescu approved these changes

2022-12-15 21:21 UTC, crissty21 commented
this is the final form.
let me know if I need to modify something

2022-12-16 08:04 UTC, CristianIonutIonescu approved these changes

2022-12-19 12:07 UTC, enachebogdan approved these changes

2023-03-08 17:07 UTC, closed without merging