tema2DHoka added
CppRemoteLearning/2022 pull request #20
Opened 2022-12-14 15:09 UTC by radavid2017

2022-12-14 17:10 UTC, CristianIonutIonescu requested changes
Thank you for the PRs. Glad to see that you used regex, STL algorithms and lambda functions.

I have left several comments that need to be addressed.
Also do NOT remove the codeowners files.

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema1DHoka/.gitignore
> +.github
You can have only one .gitignore in project root folder. This won't work

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/.gitignore
> +build
Same as above

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/file.cpp
> +    else cout << "Nu s-a deschis fisierul\n";
Event though is correct add {} to else

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/file.cpp
> +        //     my_file << itr->getNume() << " " << itr->getCantitate() << " " << itr->getPret() << endl;
Is there a problem with iterators?

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/product.h
> +using namespace std;
No using namespace std

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/product.h
> +    string nume;
https://google.github.io/styleguide/cppguide.html#Declaration_Order
Check declaration order

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/product.h
> +    Product(string& nume_produs, int& cantitate_produs, int& pret_produs) : nume(nume_produs), cant(cantitate_produs), pret(pret_produs) {
No code written in header files.

Exception: inline functions, templates

2022-12-14 17:10 UTC, CristianIonutIonescu commented on tema2DHoka/store.h
> +using namespace std;
Same regarding std

2022-12-15 07:32 UTC, CristianIonutIonescu commented on tema1DHoka/.gitignore
> +.github
Actually it works. Need to update my git knowledge

2022-12-15 07:32 UTC, CristianIonutIonescu commented on tema2DHoka/.gitignore
> +build
Actually it works. Need to update my git knowledge

2022-12-15 10:44 UTC, radavid2017 commented on tema2DHoka/file.cpp
> +        //     my_file << itr->getNume() << " " << itr->getCantitate() << " " << itr->getPret() << endl;
Yes, it was giving an error: terminate called after throwing an instance of '...' bad_alloc/length_error. But now, aparently it works fine. Maybe the problem was at something else where seems like I resolved it somehow.

2022-12-15 11:01 UTC, enachebogdan commented on tema2DHoka/product.h
> +    Product& getProduct() {  return *this; }
What do you need this function for?

2022-12-15 11:12 UTC, enachebogdan commented on tema2DHoka/store.h
> +        for (auto itr = data.begin(); itr != data.end(); itr++) {
In some places you use itr++, others ++itr, it's good to be consistent in general. ++itr is the better one (you can look up the differences, it's a good read)

2022-12-15 14:13 UTC, radavid2017 commented on tema2DHoka/product.h
> +    Product& getProduct() {  return *this; }
Ah, actually I think it doesn't help me with anything..because the object itself is not private. I saw that method on stackoverflow.com and I thought it would help me to get the product through store. But it's useless actually.

2022-12-15 14:29 UTC, radavid2017 commented on tema2DHoka/store.h
> +    Store* operator=(Store&& other) noexcept {
![nagarrophoto](https://user-images.githubusercontent.com/83161606/207886233-6af993da-a49a-4192-b9fe-740c7ab267f6.png)
I saw this on course and I guessed that move construct is differentiated by that. That's the reason for doing it like this. Sorry if I missunderstood something here.

2022-12-15 14:33 UTC, radavid2017 commented on tema2DHoka/store.h
> +        for (auto itr = data.begin(); itr != data.end(); itr++) {
I changed it in some parts because I was debugging some problems on the iterations. Thanks for advice, I saw some informations about it and I think that if I am not using the initial value, it is more efficient to pre-increment.

2022-12-16 12:40 UTC, CristianIonutIonescu approved these changes

2022-12-16 15:00 UTC, closed without merging