First draft review
CppRemoteLearning/2022 pull request #21
Opened 2022-12-14 18:33 UTC by aronkis

2022-12-14 18:57 UTC, CristianIonutIonescu reviewed
Thank you for the PR.
Left some minor comments, nothing deal breaker.
Waiting to see the rest of the code

2022-12-14 18:57 UTC, CristianIonutIonescu commented on H2/include/Product.h
> +class Product
https://google.github.io/styleguide/cppguide.html#Declaration_Order

Declaration order:
public
protected
private

2022-12-14 18:57 UTC, CristianIonutIonescu commented on H2/.gitignore
> +.vscode/
Fairly sure that this doesn't work (unless github changes things since I last read about gitignore)

2022-12-15 07:32 UTC, CristianIonutIonescu commented on H2/.gitignore
> +.vscode/
I stand corrected, you can have multiple gitignore files.

2022-12-15 11:46 UTC, enachebogdan requested changes
Initial draft looks good so far, looking forward to seeing the rest of the implementation

2022-12-15 11:46 UTC, enachebogdan commented on H2/include/ProductManager.h
> +  std::list<ProductManager> productList;
nothing wrong here, just wondering why you're using list instead of vector

2022-12-15 11:46 UTC, enachebogdan commented on H2/include/Product.h
> +  Product (Product&& other) = default;
having move/copy constructors as default is perfectly fine for your class, however for the homework purpose you should try implementing them.

2022-12-15 11:46 UTC, enachebogdan commented on H2/include/Product.h
> +  Product& operator=(Product &&other);
Since you're not declaring these assignment operators "= default", you'll have to implement them as well.

2022-12-15 11:51 UTC, aronkis commented on H2/include/ProductManager.h
> +  std::list<ProductManager> productList;
because it is more efficient to remove elements from a list than from a vector

2022-12-15 12:26 UTC, CristianIonutIonescu commented on H2/include/ProductManager.h
> +  std::list<ProductManager> productList;
> because it is more efficient to remove elements from a list than from a vector

[intrigued](https://tenor.com/en-GB/view/curiosity-curious-intrigued-interested-interesting-gif-14505707)

2022-12-15 12:28 UTC, enachebogdan commented on H2/include/ProductManager.h
> +  std::list<ProductManager> productList;
sounds great, good call

2022-12-15 17:56 UTC, CristianIonutIonescu reviewed
Most of the comments are minor and don't influence the outcome of homework.
Just extra stuff

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/main.cc
> +    std::cout << (*it).first << " " << (*it).second << std::endl;
why not using it->first and it->second ?

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/main.cc
> +    std::cout << (*it).first << " " << (*it).second << std::endl;
same as above.
Bonus read about const interators and when they are used.

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/include/ProductManager.h
> +  std::list<ProductManager> productList;
following up on this:
shouldn't be a` list<Product>` instead of `list<ProductManager>` ?

Also, to not add another comment, access order again

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/main.cc
> +  std::vector<std::pair<std::string, double>> values = Handler.getValues();
what operation is performed under the hood?
Copy or move? And why?

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/main.cc
> +  values.push_back(std::make_pair(mouse.getName(), mouse.getPrice()));
code works ok as it.
Questions:
1. What operator/constructor is called under the hood? Copy or more?
2. Read about `emplace_back` method and how it would have been used here?

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/.gitignore
> +CMakeFiles/
this tells me you have built your application wrong :D

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/src/Product.cc
> +Product::Product(std::string name, double price)
read about Constructor initializer lists.
Same applies to other constructors

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/src/XMLHandler.cc
> +  std::string line;
why declaring them (line,values, tempPair) here when you might not even use them?
Restrict the lifetime of your objects to the minimum.
Also why do you need values and tempPair objects? can you store them directly in file_content?

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/src/XMLHandler.cc
> +  xmlFile.open(path_to_file_, std::ofstream::out | std::ofstream::trunc);
what if xmlFile.open fails?

2022-12-15 17:56 UTC, CristianIonutIonescu commented on H2/include/XMLHandler.h
> +  ~XMLHandler() {}
= default

2022-12-16 14:23 UTC, aronkis commented on H2/main.cc
> +    std::cout << (*it).first << " " << (*it).second << std::endl;
great thing I asked about them and forgot to use them :)

2022-12-16 15:21 UTC, aronkis commented on H2/main.cc
> +  std::vector<std::pair<std::string, double>> values = Handler.getValues();
The move operation is performed, because we do not use the Handler anymore so the compiler might discard it after the move.

2022-12-16 15:33 UTC, CristianIonutIonescu approved these changes

2022-12-16 15:44 UTC, aronkis commented on H2/main.cc
> +  values.push_back(std::make_pair(mouse.getName(), mouse.getPrice()));
1. The move operator, because after we created the copy the compiler frees up the memory immediately.
2. The `emplace_back` method does not create a temporary vector, like `push_back`, instead it appends the values directly into the vector, which means its faster and memory efficient.

2022-12-19 12:28 UTC, enachebogdan approved these changes

2022-12-19 12:43 UTC, merged