version 1.4 final
CppRemoteLearning/2022 pull request #26
Opened 2022-12-16 17:46 UTC by AlexAndrei11

Am facut un alt pull request si de asemenea un alt branch deoarece l-am stricat pe celalalt facand merge cu ce am uploadat la prima tema.

2022-12-16 19:40 UTC, CristianIonutIonescu requested changes
Encapsulate the read/write functions into a class.
I don't see the products read from file nor written. Please build the objects with what you read and write them as well

2022-12-17 05:50 UTC, AlexAndrei11 commented
Cred ca am rezolvat problema. Mie totusi imi apareau textele din fisiere si la version 1.4

2022-12-17 06:58 UTC, CristianIonutIonescu requested changes

2022-12-17 06:58 UTC, CristianIonutIonescu commented on main/main.cpp
> +    fileContents += "Ruleta 9.25 18\nFileOut FileOut FileOut";
Tema nu este completă. Folosești un string pentru a citi/scrie conținutul fișierului. Clasele tale Product și Store nu sunt folosite.

2023-03-08 17:09 UTC, closed without merging