added the basic stuff
CppRemoteLearning/2022 pull request #35
Opened 2023-03-07 11:42 UTC by Lys4nder

2023-03-08 16:46 UTC, CristianIonutIonescu reviewed
Great job with this draft. I've left some comments there but nothing that would require a `Request Change` review. 
PS: some comments that I have made regarding customers are true for products as well

2023-03-08 16:46 UTC, CristianIonutIonescu commented on products.cpp
> +bool nonAlcoholicDrinks::isSafe()
nothing wrong with them but I encourage you to read a little bit about `constexpr`

2023-03-08 16:46 UTC, CristianIonutIonescu commented on customer.cpp
> +}
nothing wrong but I suggest reading about inline methods

2023-03-08 16:46 UTC, CristianIonutIonescu commented on main.cpp
> +    system("clear");
indentation

2023-03-08 18:12 UTC, marisvali requested changes
The project as it is doesn't use polymorphism and doesn't show SOLID principles in action.

Quotes from the homework assignment that haven't been addressed:

"Extend(or implement from scratch) a general store"
"increasing income"
"Class for printing"
"customer enters shop, ask for a product"
"your code should be compliant with SOLID principles"

2023-03-08 18:12 UTC, marisvali commented on customer.cpp
> +}
This method doesn't get the discount, it applies the discount. When you have a getDiscount and a member called discount_ I immediately think getDiscount will return the value of discount_. The function name should save the reader this confusion. Maybe something like getPriceAfterDiscount or getDiscountedPrice.

2023-03-08 18:12 UTC, marisvali commented on products.hpp
> +        virtual bool isSafe() = 0;
It's fun to add new functions in the middle of the hierarchy, because it justifies the hierarchy. Only some products are beverages and only beverages are safe or not safe. Only some products are food and only foods can be eco or not. It makes sense so far.

However, now you have the following problem: the whole point of polymorphism is to use the objects of derived classes through their base class. So should the store contain a list of products? But then it can't find out if a product is safe. Then it needs to keep a list of foods and a list of beverages. But then whenever I want to do something with my whole inventory, I have to work with 2 lists instead of one. Example:

```
void clearInventory()
{
    foods.clear();
    beverages.clear();
}

int inventoryValue()
{
   int total = 0;
   for (auto food: foods)
   {
      total += food.getPrice();
   }
   for (auto beverage: beverages)
   {
      total += beverage.getPrice();
   }
}
```

Whenever a customer wants to buy a product, the store needs to check if the product is still available. Again, it needs to check which category the product belongs to then check the right list to see if the product is available. But this is exactly the problem that polymorphism tries to solve. And the point of the homework is to show how you can use polymorphism and SOLID to solve problems you would have without them.

2023-03-09 12:22 UTC, Lys4nder commented on products.cpp
> +bool nonAlcoholicDrinks::isSafe()
you mean to use constexpr for isSafe or constructor?

2023-03-09 21:39 UTC, CristianIonutIonescu reviewed
Left a couple more comments. Please have a look

2023-03-09 21:39 UTC, CristianIonutIonescu commented on customer.cpp
> +
Inline functions are usually defined inside class declaration (within the header files)

2023-03-09 21:39 UTC, CristianIonutIonescu commented on main.cpp
> +    std::vector<vegetables> veggies;
This whole block of code(reviewing from phone) is dangerous, you're assigning the addresses of these objects to another vector. If you were to limit the lifetime of your vectors, the one containing pointers to them would result in crash at best, indeterminate behavior.
You must dynamically allocate your memory for polymorphism

2023-03-09 21:39 UTC, CristianIonutIonescu commented on store.hpp
> +class printStore {
I know it's not final, but from the looks of it, you're not making use of polymorphism here. Printer shouldn't care what type of costumer or product it prints.

2023-03-18 08:00 UTC, CristianIonutIonescu approved these changes

2023-03-18 12:11 UTC, marisvali approved these changes

2023-03-18 16:18 UTC, merged