Upload homework 4
CppRemoteLearning/2022 pull request #37
Opened 2023-03-08 14:38 UTC by oprisor-adrian

2023-03-08 21:27 UTC, marisvali requested changes
The project doesn't show polymorphism or SOLID in action. There aren't multiple products. Too much is missing to provide more feedback or guidance.

Quotes from the homework assignment that haven't been addressed:

"Multiple types of products"
"Class for printing"
"In main, simulate multiple shopping situations"
"your code should be compliant with SOLID principles"

2023-03-08 21:27 UTC, marisvali commented on course_4_homework/include/customer/customer.h
> +    virtual double CheckOut(Store&) const;
CheckOut sounds like it says "perform checkout". But the function actually returns the amount that the customer has to pay. You added the comment, which means the name of the function doesn't properly describe what the function does. Try to find a better name.

2023-03-08 21:27 UTC, marisvali commented on course_4_homework/include/product.h
> +    uint8_t age_limit_;
Careful. You've defined a very flexible Product class which means there's need or room for a hierarchy of different kinds of products. This works well if you just want to have a store that works. But the point of the homework is to practice polymorphism and SOLID. I suggest making the Product class less flexible and creating a hierarchy of products.

2023-03-08 21:27 UTC, marisvali commented on course_4_homework/src/customer/customer.cc
> +  if(item.first){
The if is redundant. This makes sense in Java/C# where all objects are references and they can be null. However in C++ objects are values and item.first will always be of type Product, which will always be non-null (only Product* can be null).

2023-03-08 21:27 UTC, marisvali commented on course_4_homework/src/customer/customer.cc
> +  std::cout << "Product " << product.GetName() << " no't found!\n";
Don't write more than one instruction in a single line. C++ is very flexible and lets you do all sorts of things. But you should always put separate instructions on separate lines. Instead of
`if(auto search = shopping_cart_.find(product); search != shopping_cart_.end()){`
do
```
auto search = shopping_cart_.find(product);
if(search != shopping_cart_.end()){
```
Spelling error in "no't found".
And if you're using early returns, you can do this:
auto search = shopping_cart_.find(product);
```
  if(search == shopping_cart_.end()){
    std::cout << "Product " << product.GetName() << " no't found!\n";
    return;
  }
  if(amount == 0 || search->second - amount < 0){
    shopping_cart_.erase(product);
    return;
  }
  shopping_cart_[product] = search->second - amount;
```

2023-03-10 20:26 UTC, CristianIonutIonescu approved these changes
Although there are many things that can be addressed, I consider that the majority of the requirements were met on a level enough for me to consider the homework done.

2023-03-10 20:26 UTC, CristianIonutIonescu commented on course_4_homework/include/printer.h
> +template<class object>
Although it works this way, the scope of the requirement was to use polymorphism here.

2023-03-10 20:26 UTC, CristianIonutIonescu commented on course_4_homework/include/printer.h
> +#endif  // STORE_SIMULATOR_INCLUDE_PRINTER_H_
If you add your endif here, all below it will be included in each file you include this header. #endif should be at the end of the file

2023-03-10 20:48 UTC, oprisor-adrian commented on course_4_homework/main.cc
> +  Store store(0.0, "MyStore", "somewhere", items);
I made a little mistake here. I did some tests using smart pointers and forgot to change them. Thank you for pointing out the mistake.

2023-03-17 09:07 UTC, merged