Tema 4: extension from Tema2
CppRemoteLearning/2022 pull request #38
Opened 2023-03-08 16:08 UTC by radavid2017

2023-03-08 22:46 UTC, marisvali requested changes
The project follows the requirements fairly well. It uses polymorphism and SOLID (the derived customers don't rely on the derived products directly, they are connected through their base interfaces/classes). However, it's minimal. A few more features would be nice.

Quotes from the homework assignment that haven't been addressed:
"Class for printing ... should be extendable"

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/file.h
>      std::string name;
Since file.h/file.cpp will contain the StoreIO class, rename the files to storeio.h/storeio.cpp.
I have a curiosity regarding file.cpp so I'll leave it here. You have this code:
```
if (!store.isEmpty()) {
for (auto itr = store.getData().begin(); itr < store.getData().end(); ++itr) {
    my_file << itr->getNume() << " " << itr->getCantitate() << " " << itr->getPret() << std::endl;
}
// for (Product& product : store.getData()) {
//     my_file << product.getNume() << " " << product.getCantitate() << " " << product.getPret() << endl;
// }
```
How come you opted for the version with the iterator instead of the ranged for loop? It's not a mistake, I'm just curious.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/main.cpp
> +    Product* p2 = new Feed("Paine");
You should never use raw pointers like this, if you can avoid it. Use smart pointers, unless you have a good reason not to.
`std::unique_ptr<Customer> underAge = std::make_unique<Customer>();`
Your code as it is has memory leaks (you never call delete). In this case it doesn't affect the execution, the application ends immediately and the OS will free the memory. But the cases where memory leaks are acceptable are rare and decided by experts. For now, consider all memory leaks forbidden.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/product.cpp
> +    age_restricted = other.age_restricted;
The field is initialized here, but it's not initialized in the default constructor. The derived classes initialize it, yes. But someone who derives from the class might not remember to do that. You are relying on the fact that another programmer will know the convention is that any derived class must initialize this member. Don't rely on conventions when you can enforce something. It's very dangerous to leave any variable uninitialized. It will get a random value. Maybe with one value the software will work, maybe with another, it won't. This is the most expensive bug: the one that happens only once in a while for no apparent reason. Never leave any variable uninitialized.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/product.h
>  class Product {
The Product class has no pure virtual function, so I can create this:
Product product("etc", 3, 2);
Which might not be what you intended. You have two derived products: Alcohol and Feed. One is age restricted, one isn't. They don't differ from Product in any other way, so they cover all possible products. In fact, a plain Product object will have its age_restricted member uninitialized.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/store.cpp
> +Store::Store(std::vector<Product> data_store, int income_store) : data(data_store), income(income_store) {
Make a habit to pass all containers as const&, otherwise you're making unnecessary copies.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/underage.cpp
> +    }
If you have only two options, use if instead of switch.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/underage.cpp
> +        return 0;
Use enums instead of integers. Google around to see why this is a good idea and how to do it in C++.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/underage.h
> +        int askForProduct(std::string const& name, Store& store) const noexcept;
Use the override keyword on functions that override virtual functions. C++ allows us not to do it because of backwards compatibility, but everyone should use the override keyword in these cases.

2023-03-08 22:46 UTC, marisvali commented on tema2DHoka/main.cpp
> +    store.addProduct(*p1);
You're slicing your object here (https://www.learncpp.com/cpp-tutorial/object-slicing/). The whole point of polymorphism is for the store to hold a collection of pointers to Product objects, and each object can be any derived type. The store will treat them all the same, but they will act different when they need to. If you hold a collection of values, not pointers, you don't have polymorphism anymore.

2023-03-09 20:12 UTC, radavid2017 commented on tema2DHoka/file.h
>      std::string name;
Honestly, my first try was with the iterator. Before adding the commented code which is the second option, my first way had some error and somehow after a while of code editing the loop with the iterator worked well. So I chose to let with iterator because it seems more professionally and maybe is efficient with the memory, but I am not sure yet.

2023-03-09 20:15 UTC, radavid2017 commented on tema2DHoka/main.cpp
> +    Product* p2 = new Feed("Paine");
I will take it under consideration, thank you for giving the information. I was wondering why does not appear the destructor message in the console, but now it make sense.

2023-03-09 20:35 UTC, radavid2017 commented on tema2DHoka/product.cpp
> +    age_restricted = other.age_restricted;
I took that under consideration and have just modified the constructors to work properly in any situation. Thank you for making me understand its initialization importance.

2023-03-09 20:38 UTC, radavid2017 commented on tema2DHoka/product.h
>  class Product {
Yes, I was wondering if just initializing some methods with "virtual" would make the class abstract. Now I see the main feature of an abstract class. I chose to define the destructors of the Product and Customer as pure virtual functions. I hope it is okay. If not, please let me know.

2023-03-09 20:42 UTC, radavid2017 commented on tema2DHoka/store.cpp
> +Store::Store(std::vector<Product> data_store, int income_store) : data(data_store), income(income_store) {
Thank you for telling me about it. I will look to make it a habit.

2023-03-10 12:13 UTC, radavid2017 commented on tema2DHoka/adult.cpp
> +}
I added restrictions to underage and adult constructors. The method named isAdult() is removed to avoid conflicts and ambiguity.

2023-03-10 12:14 UTC, radavid2017 commented on tema2DHoka/alcohol.cpp
> +}
I will take it under consideration and from now on I will write the code just in english.

2023-03-10 12:17 UTC, radavid2017 commented on tema2DHoka/customer.h
> +class Customer {
I made the destructors of bases as pure virtual functions. I hope it was a good idea to make it abstract class. If not, let me know.

2023-03-10 12:18 UTC, radavid2017 commented on tema2DHoka/main.cpp
> +    store.addProduct(*p1);
I worked this time with smart pointers, and it seems to work just as it should be now.

2023-03-10 12:22 UTC, CristianIonutIonescu commented on tema2DHoka/customer.h
> +class Customer {
Although you can make destructors pure virtual, you'd still need to declare a function body for them, which somehow defeats the purpose of pure virtual functions. I'd keep them just virtual and that's it.

2023-03-10 19:36 UTC, marisvali approved these changes
This implements enough of the requirements to qualify as done. There are tweaks that can be made here and there, but this homework already took longer to implement than we estimated, so we might as well stop here for now.

2023-03-10 19:36 UTC, marisvali commented on tema2DHoka/store.h
> +    std::vector<Product*> data;
At first I thought this as an error, but now I see that there's no memory leak. The store just holds references to Products, and the owner of the Product objects is the main function. But it would make more sense for the store to own the products, so a vector of unique_ptr.

2023-03-10 19:36 UTC, marisvali commented on tema2DHoka/store.h
>      ~Store();
You don't need any of these.

2023-03-10 19:36 UTC, marisvali commented on tema2DHoka/storeio.cpp
>  }
The StoreIO class isn't showcased in main. It would be nice to see it used.

2023-03-10 20:27 UTC, CristianIonutIonescu approved these changes
As Vali said, even though there are many things that could be improved the curent status of the PR is enough for me to consider the homework done

2023-03-10 20:40 UTC, radavid2017 commented on tema2DHoka/customer.cpp
> +        std::cout<<"Produsul unfound\n";
I am sorry, it seems some words escaped from editing. Maybe it is because of a little fatigue.

2023-03-10 20:41 UTC, radavid2017 commented on tema2DHoka/main.cpp
> -    StoreIO storeIO = StoreIO("/home/yuda/2022/tema2DHoka/date.txt");
I had some problems in the previous homework with this. I was giving the relative path and the file was not updated. I will try to use the relative path from now on, I hope it will work these times.

2023-03-10 20:43 UTC, radavid2017 commented on tema2DHoka/store.h
> +    std::vector<Product*> data;
This was a question which dropped out of my mind. I was thinking about it but I forgot to ask. Thank you for letting me know this information!

2023-03-10 20:45 UTC, radavid2017 commented on tema2DHoka/storeio.cpp
>  }
It was used in the second homework, but it works very similar with the Write system that has been implemented now.

2023-03-10 20:49 UTC, merged