HW5 lpitu
CppRemoteLearning/2022 pull request #41
Opened 2023-03-12 14:14 UTC by Lys4nder

changed names according to naming convention

2023-03-12 18:43 UTC, CristianIonutIonescu reviewed
I have just reviewed the code from coding standard point of view. I might have missed some mistakes as I reviewed from phone but should give you an overview of what you need to improve

2023-03-12 18:43 UTC, CristianIonutIonescu commented on store.cpp
> +    customers_.emplace_back(std::move(cust));
As Vali explained in the previous lesson std:: move does nothing

2023-03-12 18:43 UTC, CristianIonutIonescu commented on customer.hpp
> +        float GetDiscount(float sum);
Mark it as override

2023-03-12 18:43 UTC, CristianIonutIonescu commented on customer.hpp
> +        float GetDiscount(float sum);
Mark it as override

2023-03-12 18:43 UTC, CristianIonutIonescu commented on customer.hpp
> +        inline virtual float GetDiscount() { return 0;}
Don't inline virtual functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on customer.hpp
> +#include <iostream>
Don't include headers that are not needed in header files. Include them where you use them i.e source files

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +#include <iostream>
Don't include headers that you don't use in header files. Include them in source files

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline virtual void PrintNameQuantity() {std::cout << "You have " << GetQuantity() << " of " << GetName() << '\n';}
Don't inline virtual functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline virtual bool IsSafe() = 0;
Don't inline virtual functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline bool IsSafe() { return true; }
Don't inline virtual functions, mark overriden functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline bool IsSafe() { return false; }
Don't inline virtual functions, mark overriden functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline virtual bool IsEco() = 0;
Don't inline virtual functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        virtual void SetEco() = 0;
Don't inline virtual functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        inline bool IsEco() { return eco_; }
Don't inline virtual functions, mark overriden functions

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        void SetEco();
Mark it as override

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        bool IsEco() { return eco_; }
Mark it as override

2023-03-12 18:43 UTC, CristianIonutIonescu commented on products.hpp
> +        void SetEco();
Mark it as override

2023-03-12 18:43 UTC, CristianIonutIonescu commented on store.cpp
> +    products_.emplace_back(std::move(prod));
As Vali explained in the previous lesson std:: move does nothing

2023-03-13 09:30 UTC, Lys4nder commented on store.cpp
> +    products_.emplace_back(std::move(prod));
std::move does something i believe, because Store class has a private member of unique pointer and I am passing the ownership when creating the products vector

2023-03-15 18:48 UTC, CristianIonutIonescu requested changes
Main problem with the current solution is throwing ints and catching them.

2023-03-15 18:48 UTC, CristianIonutIonescu commented on store.cpp
> +        throw 2;
Don't throw random numbers as exception.

2023-03-15 18:48 UTC, CristianIonutIonescu commented on store.cpp
> +    catch (int & e) {
Not a good pattern to handle exceptions. Create custom exceptions inheriting from std::runtime_error and handle each of it in a separate catch

2023-03-15 18:48 UTC, CristianIonutIonescu commented on store.hpp
> +#include <iostream>
Don't include what you don't use. Include it in source file.
Also, you can forward declare the client and product and include the header in source file.

2023-03-16 08:10 UTC, CristianIonutIonescu commented on store.cpp
> +    products_.emplace_back(std::move(prod));
yes, you are right, you need the std::move here

2023-03-16 08:30 UTC, CristianIonutIonescu requested changes
adding additional issues

2023-03-16 08:30 UTC, CristianIonutIonescu commented on store.cpp
> +            if (cust->GetName().empty())
instead of allowing a customer to have an empty name and throwing here, you'd better not allow creating a customer without name. Same for product

2023-03-16 08:30 UTC, CristianIonutIonescu commented on store.cpp
> +            cust->SpendMoney(prod->GetPrice() * quantity * (-1)); //give money back to customer
You are breaking S from SOLID here:
`every class, module, or function in a program should have one responsibility/purpose in a program.`
Write proper methods for returning the money.

2023-03-16 08:30 UTC, CristianIonutIonescu commented on store.cpp
> +    catch(int &e) {
not a valid case to throw and catch

2023-03-16 08:30 UTC, CristianIonutIonescu commented on store.cpp
> +void Store::SellProduct(const std::string& productName, int quantity, const std::string& customerName)
How do you inform your caller that the client bought something and give him the chance to recover from a failure? By caller I mean the code where you call this method. It cannot read the console output

2023-03-16 09:51 UTC, CristianIonutIonescu requested changes
adding one more comment

2023-03-16 09:51 UTC, CristianIonutIonescu commented on store.cpp
> +            if (inv->GetName().empty())
you are dereferencing a pointer without checking if it's null. Same for products

2023-03-16 09:57 UTC, CristianIonutIonescu commented on store.cpp
> +void Store::RegisterMoney(float s)
find a better name for the argument instead of `s`

2023-03-16 11:22 UTC, CristianIonutIonescu commented on store.hpp
> +class PrintStore {
Don't name classes after an action but after an object.
PrintStore -> StorePrinter

2023-03-16 20:48 UTC, Lys4nder commented on store.cpp
> +void Store::SellProduct(const std::string& productName, int quantity, const std::string& customerName)
let me know if the current implementation is correct

2023-03-17 19:12 UTC, CristianIonutIonescu commented on store.cpp
> +void Store::SellProduct(const std::string& productName, int quantity, const std::string& customerName)
the caller (your main function) still doesn't know if the transaction was successful or not

2023-03-17 19:13 UTC, CristianIonutIonescu commented on store.cpp
> +    }
these can be done in the catch bodies of your exceptions, no need to handle them separately

2023-03-17 19:15 UTC, CristianIonutIonescu commented on customer.cpp
> +    }
if you're catching here, the caller doesn't know if the money was spent or not. You can catch this exception upstream of this method (where it's called)

2023-03-17 19:16 UTC, CristianIonutIonescu approved these changes
Minor changes that need to be done. Approving it but make sure you fix them by next homework if you cannot do it by tomorrow morning.

2023-03-17 19:21 UTC, CristianIonutIonescu commented on store.cpp
> +        std::cout << "Customer: " << cust->GetName() << " with " << cust->GetMoneySpent() << " spent money.\n";
same here regarding pointers

2023-03-18 16:23 UTC, merged