Upload homework 5
CppRemoteLearning/2022 pull request #43
Opened 2023-03-13 19:48 UTC by oprisor-adrian

To do: 
- [ ] Code styling
- [ ] Use a file handler in FilePrinter class ( File* )
- [ ] Error handling

2023-03-16 14:16 UTC, enachebogdan requested changes
Good stuff Adrian, PR looks good in general, I expect a bit more on the exception handling part.
It's admirable that you try using multiple c++ features, discussed or not during the presentations, but make sure you don't over complicate things when it's not unnecessary.

2023-03-16 14:16 UTC, enachebogdan commented on course_5_homework/include/customer/customer.h
> +    virtual double CheckOut(Store& store);
I'm curious why you need to return the amount at the end of the checkout.

2023-03-16 14:16 UTC, enachebogdan commented on course_5_homework/src/printer/file_handler.cc
> +  return std::fread(buffer, sizeof(char), counter, stream_);
Do you need to check if the file is open for read or write before?

2023-03-16 14:16 UTC, enachebogdan commented on course_5_homework/include/store.h
> +enum Status{
have a look into enum class as well, and why is it better than plain enum.

2023-03-16 14:16 UTC, enachebogdan commented on course_5_homework/src/store.cc
> +std::tuple<bool, std::unique_ptr<Product>> Store::Exist(const std::string& id) const{
Same discussion for Exist, not sure what you are trying to accomplish, maybe you could write this in a clearer way.

2023-03-16 14:53 UTC, oprisor-adrian commented on course_5_homework/main.cc
> +FilePrinter Logger::log_("course_5_homework/data/log.txt");
Here _log__ is also a static data member and can be initialized outside the class using the scope resolution operator. I did this because I want the _log__ to be initialized only once in the entire program and then used (calling the _Log_ method, also static) wherever it is needed just by including the header. I can't access the _log__ from an instance of Logger object.

2023-03-16 14:58 UTC, enachebogdan commented on course_5_homework/main.cc
> +FilePrinter Logger::log_("course_5_homework/data/log.txt");
The static part is handled right, I understand what you're trying to do and it's perfectly fine from that perspective, I was just curious about the "private" access modifier of log_. I would expect a compile error when you try to access from outside the class, so I was going to suggest maybe another static function to initialize it.

2023-03-16 15:16 UTC, enachebogdan commented on course_5_homework/include/customer/customer.h
> +class Customer: virtual public Printable{
I did suggest in my presentation that you look up virtual inheritance, and I'm glad you did. I thought maybe I was missing the "diamond" inheritance problem here

2023-03-16 15:16 UTC, oprisor-adrian commented on course_5_homework/include/printer/file_handler.h
> +inline std::FILE* FileHandler::GetStream() const {
In _Logger_ class i access the _std::FILE*_ through _FilePrinter_ class to allow me to access the _FileWrite_ method directly, and that method could not be constant. 
I don't know why I chose to do in this way. I'll remake it and remove/modify _GetStream()_ method. ^_^

2023-03-16 16:38 UTC, oprisor-adrian commented on course_5_homework/src/printer/file_printer.cc
> +        throw std::runtime_error("error: buffer_size != std::strlen(buffer) when printing in file.");
The error had to be caught in _main.cc_. I'll add more examples in _main_ to show that.

2023-03-16 16:49 UTC, oprisor-adrian commented on course_5_homework/src/printer/file_handler.cc
> +  return std::fread(buffer, sizeof(char), counter, stream_);
Yes! I'll add a check before trying to read from file.

2023-03-16 17:51 UTC, oprisor-adrian commented on course_5_homework/src/customer/customer.cc
> +    return {true, std::make_unique<Product>(*search->second)};
The main purpose of the function is to check if there is a product identified by the id in the shopping cart and then return the product so that processing can be done on it. I'll split in two function: _FindProduct()_ that tell me if found a product by _id_ and a _GetProduct()_ method  that return the product.

2023-03-17 07:06 UTC, enachebogdan requested changes
I've added just a couple more comments, things look good, almost ready to approve.

2023-03-17 07:06 UTC, enachebogdan commented on course_5_homework/main.cc
> +    store.AddProduct(prod_01,"cod_prod_1");
I know this is just an example/homework project, but in general you should add try/catch block for every function that can throw, not just when you know it will fail.

2023-03-17 07:06 UTC, enachebogdan commented on course_5_homework/main.cc
> +    premium_customer.AddToCart("cod_prod_1", prod_01);
AddToCart can throw an exception, you should try/catch

2023-03-17 07:08 UTC, enachebogdan commented on course_5_homework/src/printer/file_handler.cc
> +  return std::fread(buffer, sizeof(char), counter, stream_);
Actually I can see my comment is not very clear, I meant to ask if there is a need to check if the open mode is read or write, before trying to read or write

2023-03-17 07:10 UTC, enachebogdan commented on course_5_homework/include/customer/customer.h
> +    virtual double CheckOut(Store& store);
Maybe I have missed it, but I haven't seen the returned value used anywhere in your code, so I was thinking maybe it could be a simple void.

2023-03-17 07:21 UTC, oprisor-adrian commented
I tried to use forward declaration but encountered errors when I was running. I checked if the class was fully-declared before making the inheritance, but there were still errors. Maybe I missed something . In the future I will try to use forward-declaration.

2023-03-17 07:23 UTC, oprisor-adrian commented on course_5_homework/include/customer/customer.h
> +    virtual double CheckOut(Store& store);
I got an example in _main.cc_. The function _CheckOut()_ was renamed in _CompletePurchase()_.
`try{
      std::cout << "Premium customer has to pay: " << premium_customer.CompletePurchase(store) << "\n";
      premium_customer.CompletePurchase(store); // try to complete purchases process again (shopping cart will be empty)
    }
    catch (std::runtime_error& e){
      Logger::Log(e.what());
    }`

2023-03-17 07:48 UTC, oprisor-adrian commented on course_5_homework/src/printer/file_handler.cc
> +  return std::fread(buffer, sizeof(char), counter, stream_);
I understand now what to do. My last commit fix that.

2023-03-17 08:01 UTC, enachebogdan approved these changes
I'm approving your PR, great job with the homework.

2023-03-17 09:07 UTC, merged