Upload homework 6
CppRemoteLearning/2022 pull request #46
Opened 2023-03-21 18:48 UTC by oprisor-adrian

TO DO:
- [ ] code refactoring
- [ ] integrating google test
- [ ] writing unit tests

2023-03-22 13:37 UTC, marisvali requested changes
Looking through the changes it seems like you refactored the code a lot. Normally this makes sense, but for this homework you shouldn't do that. The purpose for this homework is to keep as much as you can from the original author, make only the changes needed to fix bugs. This is in order to simulate the job experience. When you work with someone else's code at a job, you will often not like their style or solutions, or have good reasons to disagree with their entire approach. However, most of the time you cannot refactor things. Either you are not given enough time or enough permissions. So for this homework we want to simulate this situation where you have to adapt as much as possible to the original code. Unfortunately this means many of the changes you made have to be reverted and only bugfixes kept.

2023-03-22 18:59 UTC, enachebogdan reviewed
Code looks good so far, I've added some questions just to check how you fixed some issues. I'll have another look once you add more unit tests.

2023-03-22 18:59 UTC, enachebogdan commented on include/shared.h
> +        template<class Y> friend class shared_ptr;
Interesting idea to access private data of "other" with a different type (Y) than the current class template(T).
Do you think there is another way around this problem, without using friend?

2023-03-22 18:59 UTC, enachebogdan commented on include/shared.h
> +    this->reset();
Did you encounter any error with the old logic? What was the problem/fix

2023-03-22 18:59 UTC, enachebogdan commented on include/shared.h
> +      count = new int(1);
Same question here, please describe what was wrong with the old version and how you fixed it.

2023-03-22 18:59 UTC, enachebogdan commented on src/store.cc
> +    if ((*result->first) == *product)
Same question here, please explain what was the problem with comparing the pointers instead of comparing the objects pointed to.

2023-03-22 18:59 UTC, enachebogdan commented on tests/store_test.cc
> +  EXPECT_EQ(store.GetBalance(), 124);
Good job integrating the unit test lib. I hope you plan adding tests for all the functions required in the homework.
I see you've added a test file just for store.cpp, which is good. It's encouraged to have unit test for different classes in different files.

2023-03-22 20:05 UTC, oprisor-adrian commented on include/shared.h
> +      count = new int(1);
First I added an _if_ statement before decrementing the _counter_ to check if a shared_ptr exists and to prevent the decrementation of nullptr. Then I added an initialization to _count_ because after calling reset the current shared_ptr no longer shares ownership of the managed object. So he is the only shared_ptr object managing the null pointer.

2023-03-22 20:07 UTC, oprisor-adrian commented on include/shared.h
> +    this->reset();
Same explanation as at _reset()_ method.

2023-03-22 20:22 UTC, oprisor-adrian commented on include/shared.h
> +        template<class Y> friend class shared_ptr;
Yep. I can use _use_count()_ to access the counter and _*other_ to access the managed object of _shared_ptr<Y>& other_ to create a copy.
I didn't see the _use_count()_ implementation earlier.

2023-03-23 16:52 UTC, enachebogdan approved these changes
Great job Adrian, I had a look at the tests and they look good overall, hope I didn't miss anything.
Just added 2 small questions, but nothing that important, so I'm approving your PR, homework is considered done.

2023-03-23 16:52 UTC, enachebogdan commented on include/shared.h
> +    data = new T(*other);
what happens if *other is nullptr?

2023-03-23 16:52 UTC, enachebogdan commented on include/unique.h
> +        T* get() const; // getter
should you return const pointer?

2023-03-23 18:02 UTC, oprisor-adrian commented on include/shared.h
> +    data = new T(*other);
I think that would result in an error because _data = new T(*other)_ will attempt to dereference a null pointer.
This can be solved by checking if _other_ is different by null pointer before the copied to be done.

2023-03-23 18:31 UTC, oprisor-adrian commented on include/unique.h
> +        T* get() const; // getter
Const pointer would prevent _unic_ptr_ managed resources from modifies. That is good if I want to provide a way to access the resource in read-only mode. Also if I have a function that modifies the state of the unique pointer, can no longer be called because of const. 
In my project _get()_ method can return a const pointer because I don't modify the state anywhere. 
As a general rule, If I can say it like that and after I google it a bit, the _get_ method should return a non-const pointer to managed object to allow the user to modify the object. On the other side, if the smart pointer is const, _get_ should return a const pointer.

2023-03-23 21:17 UTC, enachebogdan commented on include/unique.h
> +        T* get() const; // getter
I agree with you, usually if a class holds a pointer I would not advise exposing it non-const outside of the class (or exposing a non-const reference to an internal member). But since our class is a smart pointer, we don't want it to restrict the access in any way, we just want to take advantage of RAII design.

2023-03-25 06:53 UTC, merged