Dhoka Debug hw
CppRemoteLearning/2022 pull request #49
Opened 2023-03-22 13:48 UTC by radavid2017

- [ ] Compile errors resolved
- [ ] Runtime errors resolved
- [ ] gtest successfully installed
- [ ] unit tests implemented

2023-03-22 14:23 UTC, CristianIonutIonescu reviewed
Left some comments, most important ones are regarding the increasing of counter in move operations and the change of the return type for use_count. 
Also, as you chose to put the `const` on the right of what "constifies", make sure you're consistent across your code and don't change your style afterwards.

2023-03-22 14:23 UTC, CristianIonutIonescu commented on pointers/shared_ptr.h
> +    (*counter)++;
Why do you increase the counter in a move operation?
When moving you take the data from the old pointer and assign it to the new one leaving the old one empty.
Add some debugging and unit tests to this case and see if I'm right.

2023-03-22 14:23 UTC, CristianIonutIonescu commented on pointers/unique_ptr.h
> +#include "shared_ptr.h"
why did you include shared_ptr header in our unique_ptr header?

2023-03-22 14:23 UTC, CristianIonutIonescu commented on main.cpp
> +    /* DEBUG STAFF */
STUFF*

2023-03-22 14:23 UTC, CristianIonutIonescu commented on pointers/shared_ptr.h
> +#include <iostream>
I'd prefer at the end of the homework for this to be removed if possible. Alongside couts in constructors/operators/methods

2023-03-22 14:23 UTC, CristianIonutIonescu commented on pointers/shared_ptr.h
> +    size_t* use_count() const noexcept;   //number of different shared_ptr instances
the return type of use_count was correct: https://en.cppreference.com/w/cpp/memory/shared_ptr/use_count

2023-03-22 14:34 UTC, radavid2017 commented on pointers/unique_ptr.h
> +#include "shared_ptr.h"
It was added by the author, and I had compile error detecting the header. I just looked to solve the compile error, but if I would have looked carefully, I could delete the include too. It is not needed there.

2023-03-22 14:38 UTC, CristianIonutIonescu commented on pointers/shared_ptr.h
> +#include <iostream>
I figured much, that's why I didn't told you to remove them right away :)

2023-03-22 19:43 UTC, radavid2017 commented on pointers/shared_ptr.h
> +    size_t* use_count() const noexcept;   //number of different shared_ptr instances
Sorry for that, I didn't know. It is restored in the last commit added.

2023-03-24 08:02 UTC, CristianIonutIonescu requested changes
Homework looks good, address the comments I've left and it should be ok.

2023-03-24 08:09 UTC, CristianIonutIonescu commented on hello_test.cc
> +}
this is not needed anymore, you already implemented tests with GTests

2023-03-24 10:20 UTC, radavid2017 commented on tests/data.h
> +        customer = ::make_shared<UnderageCustomer>(name, age, budget);
When the input parameter of age is < 18 the code catch the exception of invalid input because of the age (Premium and Regular must have age > 18, this is what the author decided in the constructors). 

This code is written with automatized strategy for creating some data to test the functionalities.

However, I think I will delete this file and refactor the tests for the store, products and customers as well because now it seems to have a lack of readability and is too hard to read the tests and what they throw all integrated in one method. 

Thank you for catching my attention on this point.

2023-03-24 10:32 UTC, radavid2017 commented on tests/data.h
> +
Thank you for the advice and documentation suggestion. I will take time and read about these topics.

2023-03-24 18:20 UTC, CristianIonutIonescu reviewed
2 more comments left, for completeness sake

2023-03-24 18:20 UTC, CristianIonutIonescu commented on tests/customer.cc
> +TEST_F(TestCustomer, RegularBuy) {
I would add another test, just for the sake of completeness, your customer has a method `getTotalCost()` which is overriden in the derived classes. I would test the correctness of it too (for each type of client)

2023-03-24 18:20 UTC, CristianIonutIonescu commented on tests/store.cc
> +TEST_F(TestStore, Purchase_SUCCES) {
I would make sure the income is correctly increased as well (I know there's a setter for it, but seems it's not used).
Same for refunds (didn't want to add another comment)

2023-03-24 18:22 UTC, CristianIonutIonescu approved these changes
Actually, I'm already approving it. You can add the tests afterwards, but I'm not expecting any issues with it. Great work!

2023-03-24 21:02 UTC, CristianIonutIonescu commented on tests/customer.cc
> +    EXPECT_EQ(regular->getTotalCost(), 10);
This line is not entirely correct. `getTotalCost` returns a double, for checking doubles(and floats) there's a specific check in GTests,  EXPECT_DOUBLE_EQ(..) . It was created (alongside EXPECT_FLOAT_EQ) due to rounding errors that might arise when working with doubles/floats.

2023-03-24 21:03 UTC, CristianIonutIonescu commented on tests/customer.cc
> +    EXPECT_EQ(regular->getTotalCost(), 10);
LE: if getIncome also returns a double, same thing applies there

2023-03-24 21:04 UTC, CristianIonutIonescu reviewed
Additional comments.

2023-03-25 09:53 UTC, radavid2017 commented on tests/customer.cc
> +    EXPECT_EQ(regular->getTotalCost(), 10);
Thank your for letting me know. I will look again after the Assertions Reference.

2023-03-25 13:32 UTC, CristianIonutIonescu approved these changes

2023-03-25 13:47 UTC, merged