hw7 threads
CppRemoteLearning/2022 pull request #52
Opened 2023-03-27 16:55 UTC by 914-Mereu-Bianca

2023-04-05 17:44 UTC, CristianIonutIonescu requested changes
Overall ok. i have 2 major issues:
1. Move the mutexes and cond variables in restaurant class
2. You're passing way to many shared_ptrs, this looks sketchy at best, has hidden bugs most likely. I would take some time to determine who owns what and if I can pass raw pointers when needed.
Minor issues:
You create only one dish(pasta), please try to create different types of food
Implement prepare methods for your dishes.

Outside the scope of the project, please try to not write over previous homework, it's hard to read.

PS: there might be some coding style issues but due to git diff being hard to read I couldn't tell for sure, will take another look tomorrow

2023-04-05 17:44 UTC, CristianIonutIonescu commented on main.cpp
> +std::mutex mutex_dish, mutex_customer;
Why do you have the mutex and conditional variable as global? Unless I missed something you use them in restaurant class only. You should declare them as members of it

2023-04-05 17:44 UTC, CristianIonutIonescu commented on main.cpp
> +    std::thread customers[20];
Don't use a c-style array. Use vector or std:: array. Also you have 20 threads but seem to use only 5

2023-04-05 17:44 UTC, CristianIonutIonescu commented on restaurant/Restaurant.cpp
> +    std::unique_lock<std::mutex> mlock(mutex_dish);
What's the difference between unique_lock and lock_guard? In this homework I'm ok with using both, but under normal circumstances I would need a good explanation why you use one and not the other. For the sake of exercise, tell me what's the difference between them and when would you use one and not the other

2023-04-05 17:44 UTC, CristianIonutIonescu commented on restaurant/Restaurant.cpp
> +    std::lock_guard<std::mutex> guard(mutex_customer);
Why do you lock here?

2023-04-05 17:44 UTC, CristianIonutIonescu commented on restaurant/Restaurant.cpp
> +void Restaurant::deliverDish(std::queue<std::shared_ptr<Dish>> &dishes, const std::shared_ptr<Dish> &d, std::mutex &mutex_dish, std::condition_variable &cond_dish)
Why are you sending dish here? Not seeing it used

2023-04-05 18:58 UTC, 914-Mereu-Bianca commented on main.cpp
> +std::mutex mutex_dish, mutex_customer;
I wrote them there when I started writing the project and I didn't realize I could move them to the restaurant, but I'll move them now

2023-04-05 18:58 UTC, 914-Mereu-Bianca commented on restaurant/Restaurant.cpp
> +    std::unique_lock<std::mutex> mlock(mutex_dish);
The difference between them is that lock_guard automatically locks a mutex when it's created, and unlocks it when it's destructed and the unique_lock can be use to lock and unlock manually a mutex, it can also be moved and copied. I wanted to try both in this project just to see how they work, but maybe I should've used only lock_guard because I don't need all the features that unique_lock provides.

2023-04-05 18:58 UTC, 914-Mereu-Bianca commented on restaurant/Restaurant.cpp
> +    std::lock_guard<std::mutex> guard(mutex_customer);
I wasn't using atomic variable when I wrote this part, but I see now that I don't need it

2023-04-05 18:58 UTC, 914-Mereu-Bianca commented on restaurant/Restaurant.cpp
> +void Restaurant::deliverDish(std::queue<std::shared_ptr<Dish>> &dishes, const std::shared_ptr<Dish> &d, std::mutex &mutex_dish, std::condition_variable &cond_dish)
When I thought about how I should implement the program I wanted each customer to get its specific order, but later when I implemented the thread that creates dishes I realised that the program doesn't really care about what the customer ordered, so I gave up on that idea. I will remove it from there.

2023-04-07 16:54 UTC, CristianIonutIonescu approved these changes

2023-04-07 17:16 UTC, merged