HW7 Restaurant Simulation Multithreading
CppRemoteLearning/2022 pull request #53
Opened 2023-03-29 07:56 UTC by radavid2017

At first I complicated the project idea, and after some research on the internet, I redesigned the program simpler, focusing on how multithreading works.

2023-04-06 15:07 UTC, CristianIonutIonescu reviewed
so far ok, waiting for the rest of the code to be able to review it properly

2023-04-06 15:07 UTC, CristianIonutIonescu commented on tema7DHoka/restaurant.h
> +    void customer(int id);
order is:
methods
members
also, why is num_customers atomic? not seeing it used as atomic so far. Maybe in the next iteration I'll understand

2023-04-07 15:27 UTC, enachebogdan requested changes
Code looks good overall, I had some minor suggestions.
One thing you might have missed, you were supposed to have the threads for restaurant/customers run in an infinite loop, for you it seems it's just a linear run.

2023-04-07 15:27 UTC, enachebogdan commented on tema7DHoka/dish.h
> +};
does your class need a virtual destructor?
What if you do this:
Dish *d1 = new Pizza();
delete d1;

2023-04-07 15:27 UTC, enachebogdan commented on tema7DHoka/dish.h
> +class Pizza : public Dish {
even for these tiny classes, it would be better to have them each in its file.

2023-04-07 15:27 UTC, enachebogdan commented on tema7DHoka/dish_queue.cc
> +std::shared_ptr<Dish> DishQueue::remove() {
since your data type is basically a custom queue, you should name your function "pop" as well. Remove is quite misleading in this context.

2023-04-07 15:27 UTC, enachebogdan commented on tema7DHoka/restaurant.cc
> +void Restaurant::chef() {
function naming again, it should be a verb, like "cook" "prepare_dishes", something like that.

2023-04-07 16:35 UTC, radavid2017 commented on tema7DHoka/dish.h
> +};
Now that you are saying this, I tested the cases and I see a virtual destructor is a need here. If there is not a virtual destrcutor, the object is either not destroyed, either the program is calling the wrong destructor for the object (the destructor of the base if it has one).

2023-04-07 18:04 UTC, enachebogdan approved these changes

2023-04-07 18:17 UTC, merged